openapi: 3.0.0
info:
  title: Product API
  description: Simple product management API
  version: 1.0.0
paths:
  /products:
    get:
      summary: List all products
      operationId: list_products
      responses:
        "200":
          description: List of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    post:
      summary: Create a new product
      operationId: create_product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ProductCreate"
      responses:
        "201":
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
components:
  schemas:
    ProductCreate:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
          description: Name of the product
        price:
          type: number
          format: float
          description: Price of the product
        description:
          type: string
          description: Optional description of the product
    Product:
      allOf:
        - $ref: "#/components/schemas/ProductCreate"
        - type: object
          required:
            - id
          properties:
            id:
              type: integer
              description: Unique identifier for the product
